// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: coffee.proto

package coffee_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coffee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	ProdLocation  string                 `protobuf:"bytes,5,opt,name=prod_location,json=prodLocation,proto3" json:"prod_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coffee) Reset() {
	*x = Coffee{}
	mi := &file_coffee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coffee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coffee) ProtoMessage() {}

func (x *Coffee) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coffee.ProtoReflect.Descriptor instead.
func (*Coffee) Descriptor() ([]byte, []int) {
	return file_coffee_proto_rawDescGZIP(), []int{0}
}

func (x *Coffee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Coffee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Coffee) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Coffee) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Coffee) GetProdLocation() string {
	if x != nil {
		return x.ProdLocation
	}
	return ""
}

type ListCoffeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoffeesRequest) Reset() {
	*x = ListCoffeesRequest{}
	mi := &file_coffee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoffeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoffeesRequest) ProtoMessage() {}

func (x *ListCoffeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoffeesRequest.ProtoReflect.Descriptor instead.
func (*ListCoffeesRequest) Descriptor() ([]byte, []int) {
	return file_coffee_proto_rawDescGZIP(), []int{1}
}

// list all coffees
type CoffeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coffee        []*Coffee              `protobuf:"bytes,1,rep,name=coffee,proto3" json:"coffee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoffeesResponse) Reset() {
	*x = CoffeesResponse{}
	mi := &file_coffee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeesResponse) ProtoMessage() {}

func (x *CoffeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoffeesResponse.ProtoReflect.Descriptor instead.
func (*CoffeesResponse) Descriptor() ([]byte, []int) {
	return file_coffee_proto_rawDescGZIP(), []int{2}
}

func (x *CoffeesResponse) GetCoffee() []*Coffee {
	if x != nil {
		return x.Coffee
	}
	return nil
}

// get coffee by id
type CoffeeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoffeeByIdRequest) Reset() {
	*x = CoffeeByIdRequest{}
	mi := &file_coffee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeByIdRequest) ProtoMessage() {}

func (x *CoffeeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoffeeByIdRequest.ProtoReflect.Descriptor instead.
func (*CoffeeByIdRequest) Descriptor() ([]byte, []int) {
	return file_coffee_proto_rawDescGZIP(), []int{3}
}

func (x *CoffeeByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// get coffee by name
type CoffeeByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoffeeByNameRequest) Reset() {
	*x = CoffeeByNameRequest{}
	mi := &file_coffee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeByNameRequest) ProtoMessage() {}

func (x *CoffeeByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoffeeByNameRequest.ProtoReflect.Descriptor instead.
func (*CoffeeByNameRequest) Descriptor() ([]byte, []int) {
	return file_coffee_proto_rawDescGZIP(), []int{4}
}

func (x *CoffeeByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CoffeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coffee        *Coffee                `protobuf:"bytes,1,opt,name=coffee,proto3" json:"coffee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoffeeResponse) Reset() {
	*x = CoffeeResponse{}
	mi := &file_coffee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoffeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoffeeResponse) ProtoMessage() {}

func (x *CoffeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoffeeResponse.ProtoReflect.Descriptor instead.
func (*CoffeeResponse) Descriptor() ([]byte, []int) {
	return file_coffee_proto_rawDescGZIP(), []int{5}
}

func (x *CoffeeResponse) GetCoffee() *Coffee {
	if x != nil {
		return x.Coffee
	}
	return nil
}

var File_coffee_proto protoreflect.FileDescriptor

const file_coffee_proto_rawDesc = "" +
	"\n" +
	"\fcoffee.proto\"\x8a\x01\n" +
	"\x06Coffee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12#\n" +
	"\rprod_location\x18\x05 \x01(\tR\fprodLocation\"\x14\n" +
	"\x12ListCoffeesRequest\"2\n" +
	"\x0fCoffeesResponse\x12\x1f\n" +
	"\x06coffee\x18\x01 \x03(\v2\a.CoffeeR\x06coffee\"#\n" +
	"\x11CoffeeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\")\n" +
	"\x13CoffeeByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x0eCoffeeResponse\x12\x1f\n" +
	"\x06coffee\x18\x01 \x01(\v2\a.CoffeeR\x06coffee2\xb5\x01\n" +
	"\rCoffeeService\x124\n" +
	"\vListCoffees\x12\x13.ListCoffeesRequest\x1a\x10.CoffeesResponse\x124\n" +
	"\rGetCoffeeById\x12\x12.CoffeeByIdRequest\x1a\x0f.CoffeeResponse\x128\n" +
	"\x0fGetCoffeeByName\x12\x14.CoffeeByNameRequest\x1a\x0f.CoffeeResponseB\x12Z\x10./coffee_serviceb\x06proto3"

var (
	file_coffee_proto_rawDescOnce sync.Once
	file_coffee_proto_rawDescData []byte
)

func file_coffee_proto_rawDescGZIP() []byte {
	file_coffee_proto_rawDescOnce.Do(func() {
		file_coffee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coffee_proto_rawDesc), len(file_coffee_proto_rawDesc)))
	})
	return file_coffee_proto_rawDescData
}

var file_coffee_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_coffee_proto_goTypes = []any{
	(*Coffee)(nil),              // 0: Coffee
	(*ListCoffeesRequest)(nil),  // 1: ListCoffeesRequest
	(*CoffeesResponse)(nil),     // 2: CoffeesResponse
	(*CoffeeByIdRequest)(nil),   // 3: CoffeeByIdRequest
	(*CoffeeByNameRequest)(nil), // 4: CoffeeByNameRequest
	(*CoffeeResponse)(nil),      // 5: CoffeeResponse
}
var file_coffee_proto_depIdxs = []int32{
	0, // 0: CoffeesResponse.coffee:type_name -> Coffee
	0, // 1: CoffeeResponse.coffee:type_name -> Coffee
	1, // 2: CoffeeService.ListCoffees:input_type -> ListCoffeesRequest
	3, // 3: CoffeeService.GetCoffeeById:input_type -> CoffeeByIdRequest
	4, // 4: CoffeeService.GetCoffeeByName:input_type -> CoffeeByNameRequest
	2, // 5: CoffeeService.ListCoffees:output_type -> CoffeesResponse
	5, // 6: CoffeeService.GetCoffeeById:output_type -> CoffeeResponse
	5, // 7: CoffeeService.GetCoffeeByName:output_type -> CoffeeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coffee_proto_init() }
func file_coffee_proto_init() {
	if File_coffee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coffee_proto_rawDesc), len(file_coffee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coffee_proto_goTypes,
		DependencyIndexes: file_coffee_proto_depIdxs,
		MessageInfos:      file_coffee_proto_msgTypes,
	}.Build()
	File_coffee_proto = out.File
	file_coffee_proto_goTypes = nil
	file_coffee_proto_depIdxs = nil
}
