// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: coffee.proto

package coffee_service

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeService_ListCoffees_FullMethodName     = "/CoffeeService/ListCoffees"
	CoffeeService_GetCoffeeById_FullMethodName   = "/CoffeeService/GetCoffeeById"
	CoffeeService_GetCoffeeByName_FullMethodName = "/CoffeeService/GetCoffeeByName"
)

// CoffeeServiceClient is the client API for CoffeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoffeeServiceClient interface {
	ListCoffees(ctx context.Context, in *ListCoffeesRequest, opts ...grpc.CallOption) (*CoffeesResponse, error)
	GetCoffeeById(ctx context.Context, in *CoffeeByIdRequest, opts ...grpc.CallOption) (*CoffeeResponse, error)
	GetCoffeeByName(ctx context.Context, in *CoffeeByNameRequest, opts ...grpc.CallOption) (*CoffeeResponse, error)
}

type coffeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeServiceClient(cc grpc.ClientConnInterface) CoffeeServiceClient {
	return &coffeeServiceClient{cc}
}

func (c *coffeeServiceClient) ListCoffees(ctx context.Context, in *ListCoffeesRequest, opts ...grpc.CallOption) (*CoffeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoffeesResponse)
	err := c.cc.Invoke(ctx, CoffeeService_ListCoffees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) GetCoffeeById(ctx context.Context, in *CoffeeByIdRequest, opts ...grpc.CallOption) (*CoffeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoffeeResponse)
	err := c.cc.Invoke(ctx, CoffeeService_GetCoffeeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeServiceClient) GetCoffeeByName(ctx context.Context, in *CoffeeByNameRequest, opts ...grpc.CallOption) (*CoffeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoffeeResponse)
	err := c.cc.Invoke(ctx, CoffeeService_GetCoffeeByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeeServiceServer is the server API for CoffeeService service.
// All implementations must embed UnimplementedCoffeeServiceServer
// for forward compatibility.
type CoffeeServiceServer interface {
	ListCoffees(context.Context, *ListCoffeesRequest) (*CoffeesResponse, error)
	GetCoffeeById(context.Context, *CoffeeByIdRequest) (*CoffeeResponse, error)
	GetCoffeeByName(context.Context, *CoffeeByNameRequest) (*CoffeeResponse, error)
	mustEmbedUnimplementedCoffeeServiceServer()
}

// UnimplementedCoffeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeServiceServer struct{}

func (UnimplementedCoffeeServiceServer) ListCoffees(context.Context, *ListCoffeesRequest) (*CoffeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoffees not implemented")
}
func (UnimplementedCoffeeServiceServer) GetCoffeeById(context.Context, *CoffeeByIdRequest) (*CoffeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoffeeById not implemented")
}
func (UnimplementedCoffeeServiceServer) GetCoffeeByName(context.Context, *CoffeeByNameRequest) (*CoffeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoffeeByName not implemented")
}
func (UnimplementedCoffeeServiceServer) mustEmbedUnimplementedCoffeeServiceServer() {}
func (UnimplementedCoffeeServiceServer) testEmbeddedByValue()                       {}

// UnsafeCoffeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeServiceServer will
// result in compilation errors.
type UnsafeCoffeeServiceServer interface {
	mustEmbedUnimplementedCoffeeServiceServer()
}

func RegisterCoffeeServiceServer(s grpc.ServiceRegistrar, srv CoffeeServiceServer) {
	// If the following call panics, it indicates UnimplementedCoffeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeService_ServiceDesc, srv)
}

func _CoffeeService_ListCoffees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCoffeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).ListCoffees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_ListCoffees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).ListCoffees(ctx, req.(*ListCoffeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_GetCoffeeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).GetCoffeeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_GetCoffeeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).GetCoffeeById(ctx, req.(*CoffeeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeService_GetCoffeeByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServiceServer).GetCoffeeByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeService_GetCoffeeByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServiceServer).GetCoffeeByName(ctx, req.(*CoffeeByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoffeeService_ServiceDesc is the grpc.ServiceDesc for CoffeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CoffeeService",
	HandlerType: (*CoffeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCoffees",
			Handler:    _CoffeeService_ListCoffees_Handler,
		},
		{
			MethodName: "GetCoffeeById",
			Handler:    _CoffeeService_GetCoffeeById_Handler,
		},
		{
			MethodName: "GetCoffeeByName",
			Handler:    _CoffeeService_GetCoffeeByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coffee.proto",
}
